apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "experiproduct"]
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: db-service
          image: localhost:5000/db-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: DATABASE_URL
            - name: LOKI_URL
              value: "http://loki.backend.svc.cluster.local:3100"
            - name: RUST_LOG
              value: "info"

      volumes:
        - name: postgresql-data
          hostPath:
            path: /var/lib/experiproduct/postgresql
            type: DirectoryOrCreate
