apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: backend
spec:
  selector:
    app: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
